spring.application.name=feedback-management

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/feedback_db

# JWT
jwt.secret=c2VjcmV0LWtleS1mb3ItZmVlZGJhY2stbWFuYWdlbWVudC1zeXN0ZW0tMjAyNA==
jwt.expiration=86400000
